version: "3.9"

services:
  opal:
    image: obiba/opal:latest
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      OPAL_ADMINISTRATOR_PASSWORD: ${OPAL_ADMIN_PASSWORD}
      #      OPAL_PROXY_SECURE: true
      #OPAL_PROXY_HOST: localhost
      #OPAL_PROXY_PORT: 443
      CSRF_ALLOWED: "*"
      ROCK_HOSTS: "http://rock:8085"
    volumes:
      - opal_srv:/srv
    networks:
      - opalnet

  rock:
    image: obiba/rock:latest
    networks:
      - opalnet

  mongo:
    image: mongo:6.0
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    networks:
      - opalnet

  mysqldata:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${MYSQLDATA_DATABASE}
      - MYSQL_USER=${MYSQLDATA_USER}
      - MYSQL_PASSWORD=${MYSQLDATA_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - opalnet

  nginx:
    image: nginx:alpine
    depends_on:
      - opal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - opalnet

volumes:
  opal_srv:
  mysql_data:
  mongo_data:

networks:
  opalnet:
