services:
  opal:
    image: obiba/opal:latest
    depends_on:
      - rock
      - mongo
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - OPAL_ADMINISTRATOR_PASSWORD=${OPAL_ADMINISTRATOR_PASSWORD}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - ROCK_HOSTS=rock:8085
    volumes:
      - opal_srv:/srv
  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db

  rock:
    image: datashield/rock-base:latest
    environment:
    - ROCK_ID=new-stack-rock

volumes:
  opal_srv:
  mongo_data:

networks:
  opalnet: