armadillo:
  docker-management-enabled: false
  docker-run-in-container: true
  profiles:
    - name: default
      image: datashield/rock-base:latest
      port: 8085 
      host: rserver 
      package-whitelist:
        - dsBase
      function-blacklist: [ ]
      options:
        datashield:
          seed: 342325352

# required settings:
spring:
  security:
    user:
      # please change this admin password!
      password: admin!!!

  # optional settings (review spring handbook to find more):
  servlet:
    multipart:
      ## change this if your files are bigger
      max-file-size: 1000MB
      max-request-size: 1000MB

storage:
  ## to change location of the data storage
  root-dir: /data

# Match with Dockerfile volume /logs
audit.log.path: '/logs/audit.log'

stdout.log.path: '/logs/armadillo.log'

logging:
  level:
    root: INFO
    ## change to DEBUG to have more details, typically when developing
    org.molgenis: DEBUG
    ## Don't log upload data
    org.apache.coyote.http11.Http11InputBuffer: INFO
