preview:
	quarto preview

render:
	quarto render slides_opal_armadillo 
	quarto render slides_local_deploy
	quarto render slides_local_deploy_armadillo
	quarto render slides_live_deploy
	quarto render slides_profiles
	quarto render slides_build_rock
	quarto render
